server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.85
spring:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  cloud:
    config:
      enabled: false