server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    config:
        enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값(모든 요청을 트레이싱하려면1.0)

logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에traceId, spanId 추가

