server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-noti
              predicates: # 라우팅 조건
              - Path=/api/noti/**
              uri: lb://backend-noti
              filters:
                - AddAuthenticationHeader
            - id: backend-user
              predicates:
              - Path=/api/user/**
              uri: lb://backend-user
              filters:
                - AddAuthenticationHeader
            - id: backend-post
              predicates:
                - Path=/api/post/**
              uri: lb://backend-post
              filters:
                - AddAuthenticationHeader
    config:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]"

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86Gkalsdjfalkdsjfkladsjfklasdjfkwejqtklfksadnfklsadjmfkl