server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-noti
              predicates: # 라우팅 조건
              - Path=/api/noti/**
              uri: lb://backend-noti
            - id: backend-user
              predicates:
              - Path=/api/user/**
              uri: lb://backend-user
jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86Gkalsdjfalkdsjfkladsjfklasdjfkwejqtklfksadnfklsadjmfkl